os: linux
dist: trusty
sudo: required
language: C

env:
  - secure: "LoG9TdBTssl8J0CQoTiP5CylDxPxo3SCpllW3R+ODRV4asaSISPj7mWBKmvZkxpHhCr+zoswGOi5Su3ge3n8gzo6Yw2DmAXkUmQLSYlxmbwX+OKJyPI2DY/ONBWY/gd651pk8/dBCp8e6124pWvA6D1fcNCdaYatPWniM5ikq1m29NyAKimfiH3+KfOyqC906UQZ9A0nxwZlLhUFF93aUZOdvzCQg0QdkaMtHJz36+RJnYpkQ4KWMYlYjcazDtSsIlSzy6RSN7ywYfsJn5eprFsfXaJBKMMmw3bsc2ehsmxxI5jvh5XcxAK9WCHgZazvDUif0BPlIfzJ7bUlqrTe0fWtNx6MUTSpShLuytrPwt/GYiWx2G7hh0pH8Ws6HuGvZb4A9Te/XgNY1eyNo3U4Oc0hNirf87NwfJEqDEXZGR5uuGUuk4qBZnzLq7Gu42AxTWua4Da4FczDntDL+5uvlpzowc3RjpnUASroV4Hah8LCTzZBTZngE21f2/7VXm+v/ltsNBgYyyd268vvcSXmGzwhNsVN24+8wVvZev97oYRf0TgHXkepj0oSYzhZAXyBuO176K2PTn2m+FTZ0gkIxRlyzttlmmdfW5gFdZaLdfHXWPTlXXT8dN5130MzTriD5B1qRdVEtMgtbdGNLAOtKAIT8t6yIfv+12d7XUGgvLc="

before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave bsdtar liboctave-dev
  - curl -L "$URL" | sudo bsdtar zxf - -C /usr/local/MATLAB --strip-components 3
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/matlab /usr/local/bin
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/mex /usr/local/bin

script:
  - cd makefiles
  - make TARGET=Octave
  - make TARGET=MATLAB
