os: linux
dist: trusty
sudo: required
language: C

before_install:
# Install Octave
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave liboctave-dev bsdtar realpath

script:
  - 'cd .. &&
     mkdir -p paracoder &&
     curl -s -L https://github.com/fastsolve/paracoder/archive/master.zip |
     bsdtar zxf - --strip-components 1 -C paracoder &&
     cd ilupack4m'
  - octave --eval "build_milu; run tests/test_aes_fem.m"
