os: linux
dist: trusty
sudo: required
language: C

before_install:
# Install Octave
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave liboctave-dev bsdtar realpath
  - pip install requests progressbar2
# Install MEX
  - curl -s -L
    https://raw.githubusercontent.com/hpdata/gdutil/master/gd_get_pub.py |
    python - -o - -i "$MEX_LINUX" |
    sudo bsdtar zxf - -C /usr/local --strip-components 2
  - sudo ln -s -f /usr/local/MATLAB/R*/bin/mex /usr/local/bin

script:
  - cd makefiles
  - octave --eval "build_milu"
  - octave --eval "build_milu -matlab"
