language: C

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: MKL_VERSION=2017.2.050 MKLROOT=/opt/intel/compilers_and_libraries_2017.2.174/linux/mkl/
    - os: osx
      osx_image: xcode7.2

before_install:
# Install Octave and MKL
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
         sudo add-apt-repository -y ppa:octave/stable;
         sudo apt-get update -q;
         sudo apt-get install -y octave liboctave-dev bsdtar realpath;

         curl -L "$URL" | sudo bsdtar zxf - -C /usr/local --strip-components 2;
         sudo ln -s -f /usr/local/MATLAB/R2016b/bin/matlab /usr/local/bin;
         sudo ln -s -f /usr/local/MATLAB/R2016b/bin/mex /usr/local/bin;

         sudo curl -O http://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB;
         sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB;
         sudo sh -c "echo deb http://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list";
         sudo apt-get update;
         sudo apt-get install -y --no-install-recommends  intel-mkl-rt-174 intel-mkl-common-174 intel-mkl-common-c-174 intel-mkl-common-c-64bit-174 intel-tbb-libs-174;
     fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         brew tap homebrew/science;
         brew update;
         brew install --without-java octave;
     fi'

script:
  - cd makefiles
  - make TARGET=Octave && make TARGET=Octave clean
  - '[[ "$TRAVIS_OS_NAME" == "linux" ]] && make TARGET=MATLAB && make TARGET=MATLAB clean'
  - '[[ "$TRAVIS_OS_NAME" == "linux" ]] && make TARGET=Octave MKL=1 && make TARGET=Octave clean'
  - '[[ "$TRAVIS_OS_NAME" == "linux" ]] && make TARGET=MATLAB MKL=1 && make TARGET=MATLAB clean'
