sudo: required

env:
  - DEBIAN_FRONTEND=noninteractive

before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave bsdtar

script:
  - cd makefiles && make TARGET=Octave
  - echo 'addpath $PWD/matlab/ilupack' >> $HOME/.octaverc
