os: linux
dist: trusty
sudo: required
language: C

before_install:
# Install Octave
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave liboctave-dev bsdtar realpath
# Install MATLAB
  - curl -L "$URL" | sudo bsdtar zxf - -C /usr/local --strip-components 2
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/matlab /usr/local/bin
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/mex /usr/local/bin

script:
  - cd makefiles
  - make TARGET=Octave && make TARGET=Octave clean
  - make TARGET=MATLAB && make TARGET=MATLAB clean
  - make TARGET=Octave MKL=1 && make TARGET=Octave clean
  - make TARGET=MATLAB MKL=1 && make TARGET=MATLAB clean
