os: linux
dist: trusty
sudo: required
language: C
env: MKL_VERSION=2017.2.050 MKLROOT=/opt/intel/compilers_and_libraries_2017.2.174/linux/mkl/

before_install:
# Install Octave
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave liboctave-dev bsdtar realpath
# Install MATLAB
  - curl -L "$URL" | sudo bsdtar zxf - -C /usr/local --strip-components 2
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/matlab /usr/local/bin
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/mex /usr/local/bin
# Install MKL
  - sudo curl -O http://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo sh -c 'echo deb http://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends  intel-mkl-rt-174 intel-mkl-common-174 intel-mkl-common-c-174 intel-mkl-common-c-64bit-174 intel-tbb-libs-174
  #intel-mkl-eula-174 intel-mkl-gnu-174 intel-mkl-gnu-c-174 intel-mkl-gnu-rt-174
  #intel-comp-l-all-vars-174 intel-mkl-174 intel-mkl-ps-cluster-174 intel-mkl-ps-cluster-64bit-174
  #intel-mkl-ps-cluster-c-174 intel-mkl-ps-cluster-f-174
  #intel-mkl-ps-cluster-rt-174 intel-mkl-ps-common-174
  #intel-mkl-ps-common-64bit-174 intel-mkl-ps-common-c-174
  #intel-mkl-ps-common-f-174 intel-mkl-ps-common-f-64bit-174
  #intel-mkl-ps-f95-174 intel-mkl-ps-f95-common-174 intel-mkl-ps-f95-mic-174
  #intel-mkl-ps-gnu-f-174 intel-mkl-ps-gnu-f-rt-174 intel-mkl-ps-mic-174 intel-mkl-ps-mic-c-174
  #intel-mkl-ps-mic-cluster-174   intel-mkl-ps-mic-cluster-rt-174
  #intel-mkl-ps-mic-f-174
  #intel-mkl-ps-mic-rt-174 intel-mkl-ps-ss-tbb-174 intel-mkl-ps-ss-tbb-rt-174
  #intel-mkl-ps-tbb-mic-174 intel-mkl-ps-tbb-mic-rt-174 intel-mkl-psxe-050 intel-psxe-common-050

script:
  - cd makefiles
  - make TARGET=Octave && make TARGET=Octave clean
  - make TARGET=MATLAB && make TARGET=MATLAB clean
  - make TARGET=Octave MKL=1 && make TARGET=Octave clean
  - make TARGET=MATLAB MKL=1 && make TARGET=MATLAB clean
