sudo: required

language: C

env:
  - DEBIAN_FRONTEND=noninteractive

before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave bsdtar liboctave-dev
  - curl -L "$URL" | bsdtar zxf - -C /usr/local/MATLAB --strip-components 3
  - ln -s -f /usr/local/MATLAB/R2016b/bin/matlab /usr/local/bin
  - ln -s -f /usr/local/MATLAB/R2016b/bin/mex /usr/local/bin

script:
  - cd makefiles && make TARGET=Octave && make TARGET=MATLAB
