function type = MILU_Prec
% Data type definition for preconditioner

type = coder.typeof(...
    struct('p', m2c_intvec, ...
    'q', m2c_intvec, ...
    'rowscal', m2c_vec, ...
    'colscal', m2c_vec, ...
    'L', ccs_matrix, ...
    'U', ccs_matrix, ...
    'd', m2c_vec, ...
    'negE', crs_matrix, ...
    'negF', crs_matrix), ...
    [inf, 1]);